Description of essential_distMinAnglePair
Home > manopt > manifolds > essential > privateessential > essential_distMinAnglePair.m
essential_distMinAnglePair
PURPOSE
SYNOPSIS
function [tMin,fMin,tBreak1,tBreak2,Q2,tMinAll]=essential_distMinAnglePair(Q1,Q2,kFlip)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
essential_distMinAnglePair_base
This function is called by:
essential_distMinAngle
essential_distMinAnglePair_test
SOURCE CODE
function [tMin,fMin,tBreak1,tBreak2,Q2,tMinAll]=essential_distMinAnglePair(Q1,Q2,kFlip)
switch kFlip
    case 1
        %nothing to do
    case 2
        Q2([2 3 4 6],:)=-Q2([2 3 4 6],:);
    case 3
        Q2([4 5],:)=-Q2([4 5],:);
    case 4
        Q2([2 3 5 6],:)=-Q2([2 3 5 6],:);
    otherwise
        error('Value of kFlip invalid')
end
Q11=Q1(1:3,:);
Q12=Q1(4:6,:);
Q21=Q2(1:3,:);
Q22=Q2(4:6,:);
Q211=Q21*Q11';
Q212=Q22*Q12';
[tMin,fMin,tBreak1,tBreak2,tMinAll]=essential_distMinAnglePair_base(Q211,Q212);