Description of modAngle
Home > manopt > manifolds > essential > privateessential > modAngle.m
modAngle
PURPOSE
Maps any angle to the equivalent between -pi and pi
SYNOPSIS
function a=modAngle(a)
DESCRIPTION
Maps any angle to the equivalent between -pi and pi
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
essential_distMinAngle
essential_distMinAnglePair_base
essential_distMinAnglePair_test
SOURCE CODE
%Maps any angle to the equivalent between -pi and pi
function a=modAngle(a)
a=mod(a+pi,2*pi)-pi;