Description of lincomb
Home > manopt > tools > lincomb.m
lincomb
PURPOSE
Computes a linear combination of tangent vectors in the Manopt framework.
SYNOPSIS
function vec = lincomb(M, x, vecs, coeffs)
DESCRIPTION
 Computes a linear combination of tangent vectors in the Manopt framework.
 vec = lincomb(M, x, vecs, coeffs)
 M is a Manopt manifold structure obtained from a factory.
 x is a point on the manifold M.
 vecs is a cell containing n tangent vectors at x.
 coeffs is a vector of length n
 vec is a tangent vector at x obtained as the linear combination
    vec = coeffs(1)*vecs{1} + ... + coeffs(n)*vecs{n}
 See also: grammatrix orthogonalize tangentorthobasis
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
getGradient Computes the gradient of the cost function at x.
getGradientFD Computes an approx. of the gradient w/ finite differences of the cost.
fixedrankMNquotientfactory Manifold of m-by-n matrices of rank k with two factor quotient geometry.
fixedrankembeddedfactory Manifold struct to optimize fixed-rank matrices w/ an embedded geometry.
fixedrankfactory_2factors Manifold of m-by-n matrices of rank k with balanced quotient geometry.
fixedrankfactory_2factors_preconditioned Manifold of m-by-n matrices of rank k with two factor quotient geometry.
fixedrankfactory_2factors_subspace_projection Manifold of m-by-n matrices of rank k with two factor quotient geometry.
fixedrankfactory_3factors Manifold of m-by-n matrices of rank k with polar quotient geometry.
fixedrankfactory_3factors_preconditioned Manifold of m-by-n matrices of rank k with three factor quotient geometry.
fixedrankfactory_tucker_preconditioned Manifold of fixed multilinear rank tensors in Tucker format.
conjugategradient Conjugate gradient minimization algorithm for Manopt.
approxgradientFD Gradient approx. fnctn handle based on finite differences of the cost.
tCG tCG - Truncated (Steihaug-Toint) Conjugate-Gradient method
orthogonalize Orthonormalizes a basis of tangent vectors in the Manopt framework.
powermanifold Returns a structure describing a power manifold M^n = M x M x ... x M.
productmanifold Returns a structure describing a product manifold M = M1 x M2 x ... x Mn.
smallestinconvexhull Computes a minimal norm convex combination of given tangent vectors in Manopt.
SOURCE CODE
function vec = lincomb(M, x, vecs, coeffs)
% Computes a linear combination of tangent vectors in the Manopt framework.
%
% vec = lincomb(M, x, vecs, coeffs)
%
% M is a Manopt manifold structure obtained from a factory.
% x is a point on the manifold M.
% vecs is a cell containing n tangent vectors at x.
% coeffs is a vector of length n
%
% vec is a tangent vector at x obtained as the linear combination
%
%    vec = coeffs(1)*vecs{1} + ... + coeffs(n)*vecs{n}
%
% See also: grammatrix orthogonalize tangentorthobasis
% This file is part of Manopt: www.manopt.org.
% Original author: Nicolas Boumal, April 28, 2016.
% Contributors:
% Change log:
    n = numel(vecs);
    assert(numel(coeffs) == n);
    switch n
        case 0
            vec = M.zerovec(x);
        case 1
            vec = M.lincomb(x, coeffs(1), vecs{1});
        otherwise
            vec = M.lincomb(x, coeffs(1), vecs{1}, coeffs(2), vecs{2});
            for k = 3 : n
                vec = M.lincomb(x, 1, vec, coeffs(k), vecs{k});
            end
    end
end