Description of manoptsolve
Home > manopt > tools > manoptsolve.m
manoptsolve
PURPOSE
Gateway helper function to call a Manopt solver, chosen in the options.
SYNOPSIS
function [x, cost, info, options] = manoptsolve(problem, x0, options)
DESCRIPTION
 Gateway helper function to call a Manopt solver, chosen in the options.
 function [x, cost, info, options] = manoptsolve(problem)
 function [x, cost, info, options] = manoptsolve(problem, x0)
 function [x, cost, info, options] = manoptsolve(problem, x0, options)
 function [x, cost, info, options] = manoptsolve(problem, [], options)
 Depending on what is available in the Manopt problem structure, one of
 the Manopt solvers will be called and the outputs passed along. It is
 also possible to force the choice of a solver by specifying it in the
 options structure. For example:
    options.solver = @trustregions;
 Simply specify a function handle to a Manopt solver.
 See also: trustregions conjugategradient steepestdescent
CROSS-REFERENCE INFORMATION
This function calls:
canGetCost Checks whether the cost function can be computed for a problem structure.
canGetGradient Checks whether the gradient can be computed for a problem structure.
canGetHessian Checks whether the Hessian can be computed for a problem structure.
mergeOptions Merges two options structures with one having precedence over the other.
conjugategradient Conjugate gradient minimization algorithm for Manopt.
neldermead Nelder Mead optimization algorithm for derivative-free minimization.
trustregions Riemannian trust-regions solver for optimization on manifolds.
This function is called by:
low_rank_dist_completion Perform low-rank distance matrix completion w/ automatic rank detection.
nonlinear_eigenspace Example of nonlinear eigenvalue problem: total energy minimization.
preconhessiansolve Preconditioner based on the inverse Hessian, by solving linear systems.
hessianextreme Compute an extreme eigenvector / eigenvalue of the Hessian of a problem.
SOURCE CODE
function [x, cost, info, options] = manoptsolve(problem, x0, options)
% Gateway helper function to call a Manopt solver, chosen in the options.
%
% function [x, cost, info, options] = manoptsolve(problem)
% function [x, cost, info, options] = manoptsolve(problem, x0)
% function [x, cost, info, options] = manoptsolve(problem, x0, options)
% function [x, cost, info, options] = manoptsolve(problem, [], options)
%
% Depending on what is available in the Manopt problem structure, one of
% the Manopt solvers will be called and the outputs passed along. It is
% also possible to force the choice of a solver by specifying it in the
% options structure. For example:
%
%    options.solver = @trustregions;
%
% Simply specify a function handle to a Manopt solver.
%
% See also: trustregions conjugategradient steepestdescent
% This file is part of Manopt: www.manopt.org.
% Original author: Nicolas Boumal, Aug. 13, 2014.
% Contributors:
% Change log:
    % At the very least, we need a cost function.
    if ~canGetCost(problem)
        error('The problem structure must specify a cost function.');
    end
    % Depending on the number of differentials available, pick a different
    % default solver.
    if ~canGetGradient(problem)
        localdefaults.solver = @neldermead;
    elseif ~canGetHessian(problem)
        localdefaults.solver = @conjugategradient;
    else
        localdefaults.solver = @trustregions;
    end
    % Merge local defaults with user options, if any.
    if ~exist('options', 'var') || isempty(options)
        options = struct();
    end
    options = mergeOptions(localdefaults, options);
    % If no initial guess was specified, prepare the empty one.
    if ~exist('x0', 'var')
        x0 = [];
    end
    % Issue the actual call.
    [x, cost, info, options] = options.solver(problem, x0, options);
end