Description of matrixlincomb
Home > manopt > tools > matrixlincomb.m
matrixlincomb
PURPOSE
Linear combination function for tangent vectors represented as matrices.
SYNOPSIS
function v = matrixlincomb(x, a1, d1, a2, d2) %#ok
DESCRIPTION
 Linear combination function for tangent vectors represented as matrices.
 function v = lincomb(x, a1, d1)
 function v = lincomb(x, a1, d1, a2, d2)
 Given a point x, two tangent vectors d1 and d2 at x, and two real
 coefficients a1 and a2, returns a tangent vector at x representing
 a1*d1 + a2*d2, if d1 and d2 are represented as matrices (or more
 generally as arrays in Matlab).
 If a2 and d2 are omitted, the returned tangent vector is a1*d1.
 The input x is actually unused.
 This function is a helper to define manifolds in Manopt.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
complexcirclefactory Returns a manifold struct to optimize over unit-modulus complex numbers.
essentialfactory Manifold structure to optimize over the space of essential matrices.
centeredmatrixfactory Linear manifold struct. for optimization over matrices with centered cols
euclideancomplexfactory Returns a manifold struct to optimize over complex m-by-n matrices.
euclideanfactory Returns a manifold struct to optimize over m-by-n matrices.
shapefitfactory Linear manifold structure for optimization over the ShapeFit search space
symmetricfactory Returns a manifold struct to optimize over k symmetric matrices of size n
grassmanncomplexfactory Returns a manifold struct to optimize over the set of subspaces in C^n.
grassmannfactory Returns a manifold struct to optimize over the space of vector subspaces.
grassmanngeneralizedfactory Returns a manifold struct of "scaled" vector subspaces.
multinomialfactory Manifold of n-by-m column-stochastic matrices with positive entries.
obliquefactory Returns a manifold struct to optimize over matrices w/ unit-norm columns.
rotationsfactory Returns a manifold structure to optimize over rotation matrices.
spherecomplexfactory Returns a manifold struct to optimize over unit-norm complex matrices.
spherefactory Returns a manifold struct to optimize over unit-norm vectors or matrices.
spheresymmetricfactory Returns a manifold struct to optimize over unit-norm symmetric matrices.
stiefelcomplexfactory Returns a manifold struct. to optimize over complex orthonormal matrices.
stiefelfactory Returns a manifold structure to optimize over orthonormal matrices.
stiefelgeneralizedfactory Returns a manifold structure of "scaled" orthonormal matrices.
stiefelstackedfactory Stiefel(k, d)^m, represented as matrices of size m*d-by-k.
elliptopefactory Manifold of n-by-n psd matrices of rank k with unit diagonal elements.
spectrahedronfactory Manifold of n-by-n symmetric positive semidefinite matrices of rank k
symfixedrankYYcomplexfactory Manifold of n x n complex Hermitian pos. semidefinite matrices of rank k.
symfixedrankYYfactory Manifold of n-by-n symmetric positive semidefinite matrices of rank k.
sympositivedefinitefactory Manifold of n-by-n symmetric positive definite matrices with
SOURCE CODE
function v = matrixlincomb(x, a1, d1, a2, d2) %#ok<INUSL>
% Linear combination function for tangent vectors represented as matrices.
%
% function v = lincomb(x, a1, d1)
% function v = lincomb(x, a1, d1, a2, d2)
%
% Given a point x, two tangent vectors d1 and d2 at x, and two real
% coefficients a1 and a2, returns a tangent vector at x representing
% a1*d1 + a2*d2, if d1 and d2 are represented as matrices (or more
% generally as arrays in Matlab).
%
% If a2 and d2 are omitted, the returned tangent vector is a1*d1.
%
% The input x is actually unused.
%
% This function is a helper to define manifolds in Manopt.
% This file is part of Manopt: www.manopt.org.
% Original author: Nicolas Boumal, July 2, 2015.
% Contributors:
% Change log:
    if nargin == 3
        v = a1*d1;
    elseif nargin == 5
        v = a1*d1 + a2*d2;
    else
        error('matrixlincomb takes either 3 or 5 inputs.');
    end
end