Description of multisym
Home > manopt > tools > multisym.m
multisym
PURPOSE
Returns the symmetric parts of the matrices in the 3D matrix X
SYNOPSIS
function Y = multisym(X)
DESCRIPTION
 Returns the symmetric parts of the matrices in the 3D matrix X
 function Y = multisym(X)
 Y is a 3D matrix the same size as X. Each slice Y(:, :, i) is the
 symmetric part of the slice X(:, :, i).
 See also: multiprod multitransp multiscale multiskew
CROSS-REFERENCE INFORMATION
This function calls:
multitransp MULTITRANSP Transposing arrays of matrices.
This function is called by:
symmetricfactory Returns a manifold struct to optimize over k symmetric matrices of size n
rotationsfactory Returns a manifold structure to optimize over rotation matrices.
stiefelfactory Returns a manifold structure to optimize over orthonormal matrices.
SOURCE CODE
function Y = multisym(X)
% Returns the symmetric parts of the matrices in the 3D matrix X
%
% function Y = multisym(X)
%
% Y is a 3D matrix the same size as X. Each slice Y(:, :, i) is the
% symmetric part of the slice X(:, :, i).
%
% See also: multiprod multitransp multiscale multiskew
% This file is part of Manopt: www.manopt.org.
% Original author: Nicolas Boumal, Jan. 31, 2013.
% Contributors:
% Change log:
    Y = .5*(X + multitransp(X));
end