Description of tangentorthobasis
Home > manopt > tools > tangentorthobasis.m
tangentorthobasis
PURPOSE
Returns an orthonormal basis of tangent vectors in the Manopt framework.
SYNOPSIS
function orthobasis = tangentorthobasis(M, x, n)
DESCRIPTION
 Returns an orthonormal basis of tangent vectors in the Manopt framework.
 function orthobasis = tangentorthobasis(M, x)
 function orthobasis = tangentorthobasis(M, x, n)
 M is a Manopt manifold structure obtained from a factory.
 x is a point on the manifold M.
 n (optional) is the dimension of the random subspace to span; by default,
   n = M.dim() so that the returned basis spans the whole tangent space.
 orthobasis is a cell of n tangent vectors at x.
 With high probability, they form an orthonormal basis of the tangent
 space at x. If necessary, this can be checked by calling
   G = grammatrix(M, x, orthobasis)
 and verifying that norm(G - eye(size(G))) is close to zero.
 Note: if extra accuracy is required, it may help to re-orthogonalize the
 basis returned by this function once, as follows:
  B = tangentorthobasis(M, x, n);
  B = orthogonalize(M, x, B);
 See also: grammatrix orthogonalize lincomb plotprofile
CROSS-REFERENCE INFORMATION
This function calls:
orthogonalize Orthonormalizes a basis of tangent vectors in the Manopt framework.
This function is called by:
getGradient Computes the gradient of the cost function at x.
getGradientFD Computes an approx. of the gradient w/ finite differences of the cost.
approxgradientFD Gradient approx. fnctn handle based on finite differences of the cost.
hessianmatrix Computes a matrix which represents the Hessian in some tangent basis.
SOURCE CODE
function orthobasis = tangentorthobasis(M, x, n)
% Returns an orthonormal basis of tangent vectors in the Manopt framework.
%
% function orthobasis = tangentorthobasis(M, x)
% function orthobasis = tangentorthobasis(M, x, n)
%
% M is a Manopt manifold structure obtained from a factory.
% x is a point on the manifold M.
% n (optional) is the dimension of the random subspace to span; by default,
%   n = M.dim() so that the returned basis spans the whole tangent space.
%
% orthobasis is a cell of n tangent vectors at x.
% With high probability, they form an orthonormal basis of the tangent
% space at x. If necessary, this can be checked by calling
%   G = grammatrix(M, x, orthobasis)
% and verifying that norm(G - eye(size(G))) is close to zero.
%
% Note: if extra accuracy is required, it may help to re-orthogonalize the
% basis returned by this function once, as follows:
%  B = tangentorthobasis(M, x, n);
%  B = orthogonalize(M, x, B);
%
% See also: grammatrix orthogonalize lincomb plotprofile
% This file is part of Manopt: www.manopt.org.
% Original author: Nicolas Boumal, April 28, 2016.
% Contributors:
% Change log:
    dim = M.dim();
    if ~exist('n', 'var') || isempty(n)
        n = dim;
    end
    assert(n >= 0 && n <= dim && n == round(n), ...
           'n must be an integer between 0 and M.dim().');
    basis = cell(n, 1);
    % With high probability, n vectors taken at random in the tangent space
    % are linearly independent.
    for k = 1 : n
        basis{k} = M.randvec(x);
    end
    % The Gram-Schmidt process transforms any n linearly independent
    % vectors into n orthonormal vectors spanning the same subspace.
    orthobasis = orthogonalize(M, x, basis);
end