Description of canGetPartialEuclideanGradient
Home > manopt > core > canGetPartialEuclideanGradient.m
canGetPartialEuclideanGradient
PURPOSE
Checks whether the partial Euclidean gradient can be computed for a problem.
SYNOPSIS
function candoit = canGetPartialEuclideanGradient(problem)
DESCRIPTION
 Checks whether the partial Euclidean gradient can be computed for a problem.
 function candoit = canGetPartialEuclideanGradient(problem)
 Returns true if the partial Euclidean gradient of the cost function can
 be computed given the problem description, false otherwise.
 See also: getPartialEuclideanGradient canGetPartialGradient
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
canGetEuclideanGradient Checks whether the Euclidean gradient can be computed for a problem.
canGetPartialGradient Checks whether the partial gradient can be computed for a given problem.
getEuclideanGradient Computes the Euclidean gradient of the cost function at x.
getPartialGradient Computes the gradient of a subset of terms in the cost function at x.
SOURCE CODE
function candoit = canGetPartialEuclideanGradient(problem)
% Checks whether the partial Euclidean gradient can be computed for a problem.
%
% function candoit = canGetPartialEuclideanGradient(problem)
%
% Returns true if the partial Euclidean gradient of the cost function can
% be computed given the problem description, false otherwise.
%
% See also: getPartialEuclideanGradient canGetPartialGradient
% This file is part of Manopt: www.manopt.org.
% Original author: Nicolas Boumal, June 28, 2016.
% Contributors:
% Change log:
    candoit = (isfield(problem, 'partialegrad') && isfield(problem, 'ncostterms'));
    if isfield(problem, 'partialegrad') && ~isfield(problem, 'ncostterms')
        warning('manopt:partialegrad', ...
               ['If problem.partialegrad is specified, indicate the number n\n' ...
                'of terms in the cost function with problem.ncostterms = n.']);
    end
end