Description of canGetGradient
Home > manopt > core > canGetGradient.m
canGetGradient
PURPOSE
Checks whether the gradient can be computed for a problem structure.
SYNOPSIS
function candoit = canGetGradient(problem)
DESCRIPTION
 Checks whether the gradient can be computed for a problem structure.
 function candoit = canGetGradient(problem)
 Returns true if the gradient of the cost function can be computed given
 the problem description, false otherwise.
 See also: canGetCost canGetDirectionalDerivative canGetHessian
CROSS-REFERENCE INFORMATION
This function calls:
canGetEuclideanGradient Checks whether the Euclidean gradient can be computed for a problem.
canGetPartialGradient Checks whether the partial gradient can be computed for a given problem.
This function is called by:
canGetDirectionalDerivative Checks whether dir. derivatives can be computed for a problem structure.
canGetSubgradient Checks whether a subgradient can be computed for a problem structure.
getDirectionalDerivative Computes the directional derivative of the cost function at x along d.
getSubgradient Computes a subgradient of the cost function at x, up to a tolerance
barzilaiborwein Riemannian Barzilai-Borwein solver with non-monotone line-search.
rlbfgs Riemannian limited memory BFGS solver for smooth objective functions.
conjugategradient Conjugate gradient minimization algorithm for Manopt.
approxhessianFD Hessian approx. fnctn handle based on finite differences of the gradient.
steepestdescent Steepest descent (gradient descent) minimization algorithm for Manopt.
trustregions Riemannian trust-regions solver for optimization on manifolds.
checkdiff Checks the consistency of the cost function and directional derivatives.
checkgradient Checks the consistency of the cost function and the gradient.
checkhessian Checks the consistency of the cost function and the Hessian.
hessianextreme Compute an extreme eigenvector / eigenvalue of the Hessian of a problem.
hessianspectrum Returns the eigenvalues of the (preconditioned) Hessian at x.
manoptsolve Gateway helper function to call a Manopt solver, chosen in the options.
SOURCE CODE
function candoit = canGetGradient(problem)
% Checks whether the gradient can be computed for a problem structure.
%
% function candoit = canGetGradient(problem)
%
% Returns true if the gradient of the cost function can be computed given
% the problem description, false otherwise.
%
% See also: canGetCost canGetDirectionalDerivative canGetHessian
% This file is part of Manopt: www.manopt.org.
% Original author: Nicolas Boumal, Dec. 30, 2012.
% Contributors:
% Change log:
%
%   June 28, 2016 (NB):
%       Added support for getPartialGradient
%
%   Nov. 1, 2016 (NB):
%       Added support for gradient from directional derivatives
    candoit = isfield(problem, 'grad') || isfield(problem, 'costgrad') || ...
              canGetEuclideanGradient(problem) || ...
              canGetPartialGradient(problem) || ...
              ... % Check if directional derivatives can be obtained, since
              ... % it is possible to compute the gradient from directional
              ... % derivatives (expensively). Here, it is not possible to
              ... % call canGetDirectionalDerivative, because that function
              ... % would then potentially call canGetGradient, thus
              ... % starting an infinite loop. As a result, we have some
              ... % code redundancy: the check below needs to be kept
              ... % equivalent to the check in canGetDirectionalDerivative.
              isfield(problem, 'diff');
end