Description of handle_light
Home > manopt > core > handle_light.m
handle_light
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
handle_light
This function is called by:
StoreDB
handle_light
SUBFUNCTIONS
function lh = addlistener(varargin)
function notify(varargin)
function delete(varargin)
function Hmatch = findobj(varargin)
function p = findprop(varargin)
function TF = eq(varargin)
function TF = ne(varargin)
function TF = lt(varargin)
function TF = le(varargin)
function TF = gt(varargin)
function TF = ge(varargin)
SOURCE CODE
classdef handle_light &lt; handle
% Trick class to hide methods inherited from the handle class
% when calling methods(myclass).
%
% Source:
% http://stackoverflow.com/questions/6621850/is-it-possible-to-hide-the-methods-inherited-from-the-handle-class-in-matlab
% Posted by sclarke81 on StackOverflow on Oct. 24, 2012.
% This file is part of Manopt: www.manopt.org.
% Original author: sclarke81, added April 3, 2013.
% Contributors:
% Change log:
   methods(Hidden)
      function lh = addlistener(varargin)
         lh = addlistener@handle(varargin{:});
      end
      function notify(varargin)
         notify@handle(varargin{:});
      end
      function delete(varargin)
         delete@handle(varargin{:});
      end
      function Hmatch = findobj(varargin)
         Hmatch = findobj@handle(varargin{:});
      end
      function p = findprop(varargin)
         p = findprop@handle(varargin{:});
      end
      function TF = eq(varargin)
         TF = eq@handle(varargin{:});
      end
      function TF = ne(varargin)
         TF = ne@handle(varargin{:});
      end
      function TF = lt(varargin)
         TF = lt@handle(varargin{:});
      end
      function TF = le(varargin)
         TF = le@handle(varargin{:});
      end
      function TF = gt(varargin)
         TF = gt@handle(varargin{:});
      end
      function TF = ge(varargin)
         TF = ge@handle(varargin{:});
      end
   end
end