Description of mergeOptions
Home > manopt > core > mergeOptions.m
mergeOptions
PURPOSE
Merges two options structures with one having precedence over the other.
SYNOPSIS
function opts = mergeOptions(opts1, opts2)
DESCRIPTION
 Merges two options structures with one having precedence over the other.
 function opts = mergeOptions(opts1, opts2)
 input: opts1 and opts2 are two structures.
 output: opts is a structure containing all fields of opts1 and opts2.
 Whenever a field is present in both opts1 and opts2, it is the value in
 opts2 that is kept.
 The typical usage is to have opts1 contain default options and opts2
 contain user-specified options that overwrite the defaults.
 See also: getGlobalDefaults
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
low_rank_dist_completion Perform low-rank distance matrix completion w/ automatic rank detection.
conjugategradient Conjugate gradient minimization algorithm for Manopt.
approxhessianFD Hessian approx. fnctn handle based on finite differences of the gradient.
linesearch Standard line-search algorithm (step size selection) for descent methods.
linesearch_adaptive Adaptive line search algorithm (step size selection) for descent methods.
linesearch_decrease Backtracking line-search aiming merely for a decrease in cost value.
linesearch_hint Armijo line-search based on the line-search hint in the problem structure.
neldermead Nelder Mead optimization algorithm for derivative-free minimization.
preconhessiansolve Preconditioner based on the inverse Hessian, by solving linear systems.
pso Particle swarm optimization (PSO) for derivative-free minimization.
steepestdescent Steepest descent (gradient descent) minimization algorithm for Manopt.
trustregions Riemannian trust-regions solver for optimization on manifolds.
hessianextreme Compute an extreme eigenvector / eigenvalue of the Hessian of a problem.
manoptsolve Gateway helper function to call a Manopt solver, chosen in the options.
SOURCE CODE
function opts = mergeOptions(opts1, opts2)
% Merges two options structures with one having precedence over the other.
%
% function opts = mergeOptions(opts1, opts2)
%
% input: opts1 and opts2 are two structures.
% output: opts is a structure containing all fields of opts1 and opts2.
% Whenever a field is present in both opts1 and opts2, it is the value in
% opts2 that is kept.
%
% The typical usage is to have opts1 contain default options and opts2
% contain user-specified options that overwrite the defaults.
%
% See also: getGlobalDefaults
% This file is part of Manopt: www.manopt.org.
% Original author: Nicolas Boumal, Dec. 30, 2012.
% Contributors:
% Change log:
    if isempty(opts1)
        opts1 = struct();
    end
    if isempty(opts2)
        opts2 = struct();
    end
    opts = opts1;
    fields = fieldnames(opts2);
    for i = 1 : length(fields)
        opts.(fields{i}) = opts2.(fields{i});
    end
end