Description of essential_costE2cost
Home > manopt > manifolds > essential > essential_costE2cost.m
essential_costE2cost
PURPOSE
Cost evaluation at X given function handle in the Essential matrix E.
SYNOPSIS
function val = essential_costE2cost(X, costE)
DESCRIPTION
 Cost evaluation at X given function handle in the Essential matrix E.
 function val = essential_costE2cost(X, costE)
 costE is the function handle for the cost function in E.
 See also: essential_egradE2egrad essential_ehessE2ehess
CROSS-REFERENCE INFORMATION
This function calls:
multiprod Multiplying 1-D or 2-D subarrays contained in two N-D arrays.
multitransp Transposing arrays of matrices.
This function is called by:
essential_svd Sample solution of an optimization problem on the essential manifold.
SOURCE CODE
function val = essential_costE2cost(X, costE)
% Cost evaluation at X given function handle in the Essential matrix E.
%
% function val = essential_costE2cost(X, costE)
%
% costE is the function handle for the cost function in E.
%
% See also: essential_egradE2egrad essential_ehessE2ehess
% This file is part of Manopt: www.manopt.org.
% Original author: Roberto Tron, Aug. 8, 2014
% Contributors: Bamdev Mishra, May 22, 2015.
    e3hat = [0 -1 0; 1 0 0; 0 0 0];
    RA = X(:,1:3,:);
    RB = X(:,4:6,:);
    E = multiprod(multiprod(multitransp(RA), e3hat), RB);
    val = costE(E);
end