Description of canGetEuclideanGradient
Home > manopt > privatetools > canGetEuclideanGradient.m
canGetEuclideanGradient
PURPOSE
Checks whether the Euclidean gradient can be computed for a problem.
SYNOPSIS
function candoit = canGetEuclideanGradient(problem)
DESCRIPTION
 Checks whether the Euclidean gradient can be computed for a problem.
 function candoit = canGetEuclideanGradient(problem)
 Returns true if the Euclidean gradient can be computed given the problem
 description, false otherwise.
 See also: canGetGradient getEuclideanGradient
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
canGetGradient Checks whether the gradient can be computed for a problem structure.
canGetHessian Checks whether the Hessian can be computed for a problem structure.
getGradient Computes the gradient of the cost function at x.
getHessian Computes the Hessian of the cost function at x along d.
SOURCE CODE
function candoit = canGetEuclideanGradient(problem)
% Checks whether the Euclidean gradient can be computed for a problem.
%
% function candoit = canGetEuclideanGradient(problem)
%
% Returns true if the Euclidean gradient can be computed given the problem
% description, false otherwise.
%
% See also: canGetGradient getEuclideanGradient
% This file is part of Manopt: www.manopt.org.
% Original author: Nicolas Boumal, Dec. 30, 2012.
% Contributors:
% Change log:
    candoit = isfield(problem, 'egrad');
end