Description of canGetHessian
Home > manopt > privatetools > canGetHessian.m
canGetHessian
PURPOSE
Checks whether the Hessian can be computed for a problem structure.
SYNOPSIS
function candoit = canGetHessian(problem)
DESCRIPTION
 Checks whether the Hessian can be computed for a problem structure.
 function candoit = canGetHessian(problem)
 Returns true if the Hessian of the cost function can be computed given
 the problem description, false otherwise.
 See also: canGetCost canGetDirectionalDerivative canGetGradient
CROSS-REFERENCE INFORMATION
This function calls:
canGetEuclideanGradient Checks whether the Euclidean gradient can be computed for a problem.
This function is called by:
trustregions Riemannian trust-regions solver for optimization on manifolds.
checkhessian Checks the consistency of the cost function and the Hessian.
hessianspectrum Returns the eigenvalues of the (preconditioned) Hessian at x.
SOURCE CODE
function candoit = canGetHessian(problem)
% Checks whether the Hessian can be computed for a problem structure.
%
% function candoit = canGetHessian(problem)
%
% Returns true if the Hessian of the cost function can be computed given
% the problem description, false otherwise.
%
% See also: canGetCost canGetDirectionalDerivative canGetGradient
% This file is part of Manopt: www.manopt.org.
% Original author: Nicolas Boumal, Dec. 30, 2012.
% Contributors:
% Change log:
    candoit = isfield(problem, 'hess') || ...
              (isfield(problem, 'ehess') && canGetEuclideanGradient(problem));
    if ~candoit && ...
           (isfield(problem, 'ehess') && ~canGetEuclideanGradient(problem))
        warning('manopt:canGetHessian', ...
               ['If the Hessian is supplied as a Euclidean Hessian (ehess), ' ...
                'then the Euclidean gradient must also be supplied (egrad).']);
    end
end