Description of getStore
Home > manopt > privatetools > getStore.m
getStore
PURPOSE
Extracts a store struct. pertaining to a point from the storedb database.
SYNOPSIS
function store = getStore(problem, x, storedb)
DESCRIPTION
 Extracts a store struct. pertaining to a point from the storedb database.
 function store = getStore(problem, x, storedb)
 Queries the storedb database of structures (itself a structure) and
 returns the store structure corresponding to the point x. If there is no
 record for the point x, returns an empty structure.
 See also: setStore purgeStoredb
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
applyStatsfun Apply the statsfun function to a stats structure (for solvers).
getApproxHessian Computes an approximation of the Hessian of the cost fun. at x along d.
getCost Computes the cost function at x.
getCostGrad Computes the cost function and the gradient at x in one call if possible.
getDirectionalDerivative Computes the directional derivative of the cost function at x along d.
getEuclideanGradient Computes the Euclidean gradient of the cost function at x.
getGradient Computes the gradient of the cost function at x.
getHessian Computes the Hessian of the cost function at x along d.
getLinesearch Returns a hint for line-search algorithms.
getPrecon Applies the preconditioner for the Hessian of the cost at x along d.
hessianspectrum Returns the eigenvalues of the (preconditioned) Hessian at x.
SOURCE CODE
function store = getStore(problem, x, storedb)
% Extracts a store struct. pertaining to a point from the storedb database.
%
% function store = getStore(problem, x, storedb)
%
% Queries the storedb database of structures (itself a structure) and
% returns the store structure corresponding to the point x. If there is no
% record for the point x, returns an empty structure.
%
% See also: setStore purgeStoredb
% This file is part of Manopt: www.manopt.org.
% Original author: Nicolas Boumal, Dec. 30, 2012.
% Contributors:
% Change log:
    % Construct the fieldname (key) associated to the queried point x.
    key = problem.M.hash(x);
    % If there is a value stored for this key, return it.
    % Otherwise, return an empty structure.
    if isfield(storedb, key)
        store = storedb.(key);
    else
        store = struct();
    end
end