Description of hashmd5
Home > manopt > privatetools > hashmd5.m
hashmd5
PURPOSE
Computes the MD5 hash of input data.
SYNOPSIS
function h = hashmd5(inp)
DESCRIPTION
 Computes the MD5 hash of input data.
 function h = hashmd5(inp)
 Returns a string containing the MD5 hash of the input variable. The input
 variable may be of any class that can be typecast to uint8 format, which
 is fairly non-restrictive.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
complexcirclefactory Returns a manifold struct to optimize over unit-modulus complex numbers.
euclideanfactory Returns a manifold struct to optimize over m-by-n matrices.
symmetricfactory Returns a manifold struct to optimize over k symmetric matrices of size n
fixedrankMNquotientfactory Manifold of m-by-n matrices of rank k with quotient geometry.
fixedrankembeddedfactory Manifold struct to optimize fixed-rank matrices w/ an embedded geometry.
fixedrankfactory_2factors Manifold of m-by-n matrices of rank k with balanced quotient geometry.
fixedrankfactory_2factors_preconditioned Manifold of m-by-n matrices of rank k with new balanced quotient geometry
fixedrankfactory_2factors_subspace_projection Manifold of m-by-n matrices of rank k with quotient geometry.
fixedrankfactory_3factors Manifold of m-by-n matrices of rank k with polar quotient geometry.
fixedrankfactory_3factors_preconditioned Manifold of m-by-n matrices of rank k with polar quotient geometry.
grassmannfactory Returns a manifold struct to optimize over the space of vector subspaces.
obliquefactory Returns a manifold struct to optimize over matrices w/ unit-norm columns.
rotationsfactory Returns a manifold structure to optimize over rotation matrices.
spherecomplexfactory Returns a manifold struct to optimize over unit-norm complex matrices.
spherefactory Returns a manifold struct to optimize over unit-norm vectors or matrices.
stiefelfactory Returns a manifold structure to optimize over orthonormal matrices.
elliptopefactory Manifold of n-by-n PSD matrices of rank k with unit diagonal elements.
spectrahedronfactory Manifold of n-by-n symmetric positive semidefinite natrices of rank k
symfixedrankYYfactory Manifold of n-by-n symmetric positive semidefinite matrices of rank k.
sympositivedefinitefactory Manifold of n-by-n symmetric positive definite matrices with
powermanifold Returns a structure describing a power manifold M^n = M x M x ... x M.
productmanifold Returns a structure describing a product manifold M = M1 x M2 x ... x Mn.
SOURCE CODE
function h = hashmd5(inp)
% Computes the MD5 hash of input data.
%
% function h = hashmd5(inp)
%
% Returns a string containing the MD5 hash of the input variable. The input
% variable may be of any class that can be typecast to uint8 format, which
% is fairly non-restrictive.
% This file is part of Manopt: www.manopt.org.
% This code is a stripped version of more general hashing code by
% Michael Kleder, Nov 2005.
% Change log:
%   Aug. 8, 2013 (NB) : Made x a static (persistent) variable, in the hope
%                       it will speed it up. Furthermore, the function is
%                       now Octave compatible.
    is_octave = exist('OCTAVE_VERSION', 'builtin');
    persistent x;
    if isempty(x) && ~is_octave
        x = java.security.MessageDigest.getInstance('MD5');
    end
    inp=inp(:);
    % Convert strings and logicals into uint8 format
    if ischar(inp) || islogical(inp)
        inp=uint8(inp);
    else % Convert everything else into uint8 format without loss of data
        inp=typecast(inp,'uint8');
    end
    % Create hash
    if ~is_octave
        x.update(inp);
        h = typecast(x.digest, 'uint8');
        h = dec2hex(h)';
        % Remote possibility: all hash bytes < 128, so pad:
        if(size(h,1))==1
            h = [repmat('0',[1 size(h,2)]);h];
        end
        h = lower(h(:)');
    else
        h = md5sum(char(inp'), true);
    end
end